<Project>
	<PropertyGroup>
		<LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
		<SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
		<CheckNotRecommendedTargetFramework>false</CheckNotRecommendedTargetFramework>
		<CheckEolTargetFramework>false</CheckEolTargetFramework>
		<DefineConstants>TRIMMING_COMPATIBLE</DefineConstants>
		<DefineConstants>AOT_COMPATIBLE</DefineConstants>
	</PropertyGroup>
	<ItemGroup>
		<AdditionalFiles Include="$(MSBuildThisFileDirectory)stylecop.json" Link="stylecop.json" />
	</ItemGroup>
</Project>
